# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Puget Sound and Vision
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! Sometimes I write about stuff here. And things.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "pugetsoundandvision.github.io" # the base hostname & protocol for your site
# twitter_username: private_zero
# github_username:  privatezero

# Build settings
markdown: kramdown
# theme: jekyll-hilmi

# Theme setting
author: Welcome to Puget Sound and Vision
nick:   Weaver
profession: "Archivist/Librarian"
tagline: "A Resource for Audiovisual Preservation!"
timezone: Pacific
baseurl: ""
feed: true

# Social links
twitter: private_zero
github: privatezero
